-- GranularJsfx.lua
-- Produces the text of Effects/Granular/GranularGen.jsfx from Core.PARAMS.
-- Pure Lua: used by the build script and by the app itself (self-installing JSFX).

local Core = require("GranularCore")
local J = {}

function J.text()
  local L = {}
  local function add(s) L[#L + 1] = s end
  local v = Core.VERSION

  -- NOTE: keep this desc string stable; the engine finds the FX by it.
  add("desc:Granular Generator (control)")
  add("tags:utility")
  add("options:gmem=GranularGen")
  add("// Granular v" .. v .. " - GENERATED by Granular.lua / tools/build.lua. Do not edit by hand.")
  add("// Audio passes through untouched. The sliders are read by the Granular action,")
  add("// which builds the grain items on this track's child tracks.")
  add("// Slider order is append-only (saved automation refers to slider numbers).")
  add("")

  for i, p in ipairs(Core.PARAMS) do
    local range
    if p.enum then
      range = string.format("<0,%d,1{%s}>", #p.enum - 1, table.concat(p.enum, ","))
    else
      range = string.format("<%.10g,%.10g,%.10g>", p.min, p.max, p.step)
    end
    add(string.format("slider%d:%.10g%s%s", i, p.def, range, p.label))
  end

  add(string.format([[

@init
jsfx_version = %d;
last_hb = 0;
last_t = 0;

@gfx 420 46
t = time_precise();
hb = gmem[0];
hb != last_hb ? ( last_hb = hb; last_t = t; );
alive = (t - last_t) < 1.5;
engine_version = gmem[1];

gfx_x = 8; gfx_y = 6;
!alive ? (
  gfx_set(1, 0.6, 0.3, 1);
  gfx_drawstr("Granular v%s - engine NOT running (run the Granular action)");
) : engine_version != jsfx_version ? (
  gfx_set(1, 0.4, 0.4, 1);
  gfx_drawstr("Granular v%s - VERSION MISMATCH with the running engine");
) : (
  gfx_set(0.5, 1, 0.5, 1);
  gfx_drawstr("Granular v%s - engine running");
);
gfx_x = 8; gfx_y = 26;
gfx_set(0.8, 0.8, 0.8, 1);
gfx_drawstr("Open the Granular window for the full UI. Sliders here can be automated.");
]], Core.version_code(v), v, v, v))

  return table.concat(L, "\n") .. "\n"
end

return J
